# Phase 3 creates deployments for shard 1 (root)
#
# helm upgrade \
#  --install \
#  --values ./hack/kind-values-phase3.yaml \
#  --namespace kcp-alpha \
#  --create-namespace \
#  alpha ./charts/kcp
#
fullnameOverride: alpha
externalHostname: "kcp.dev.local"
etcd:
  enabled: true
kcp:
  externalLogicalClusterAdminFlag: true
  image: quay.io/mangirdas/kcp-sharded
  tag: v2
 # tag: main
  hostAliases:
    enabled: true
    values:
    - hostnames:
        - "kcp.dev.local"
      ip: "10.96.180.249"
  enabled: true
  v: 12
  tokenAuth:
    enabled: true
  batteries:
    - workspace-types
    - metrics-viewer
externalCache:
  enabled: true
  cacheInternalHostname: "cache-cache.kcp-cache.svc"
sharding:
  enabled: true
  isShard: false
  isRoot: true
caBundle:
  enabled: false
  configMapName: faros.sh
  configMapKey: root-certs.pem
