# Phase 4 creates deployments for shard 1
#
# helm upgrade \
#  --install \
#  --values ./hack/kind-values-phase3.yaml \
#  --namespace kcp-alpha \
#  --create-namespace \
#  alpha ./charts/kcp
#
fullnameOverride: proxy
externalHostname: "kcp.dev.local"
etcd:
  enabled: false
kcp:
  enabled: false
kcpFrontProxy:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
# hack to run without dns
#  hostAliases:
#    enabled: true
#    values:
#    - hostnames:
#        - "kcp.dev.local"
#      ip: "10.96.169.47"
  tokenAuth:
    enabled: true
cache:
  enabled: false
certificates:
  name: certs
sharding:
  enabled: false
  isShard: false # set this to true for the all shards, false for the first (root) shard.
  isRoot: true # set this to true for the first (root) shard, false for all other shards.
  rootShardInternalHostname: "alpha.kcp-alpha.svc.cluster.local"

