apiVersion: v1
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /etc/kcp/tls/ca.crt
        server: https://kcp:6444
      name: system:admin
    contexts:
    - context:
        cluster: system:admin
        user: admin
      name: system:admin
    current-context: system:admin
    kind: Config
    preferences: {}
    users:
    - name: admin
      user:
        client-certificate: /etc/kcp-front-proxy/client-cert-for-kubeconfig/tls.crt
        client-key: /etc/kcp-front-proxy/client-cert-for-kubeconfig/tls.key
kind: Secret
metadata:
  name: shards-kcp-kubeconfig
type: Opaque
